name: 🔑 Unity 许可证激活

on: workflow_dispatch

jobs:
  request-license:
    name: 生成激活请求文件
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 📝 生成 .alf 激活文件
        uses: game-ci/unity-request-activation-file@v2
        with:
          unityVersion: 2022.3.20f1
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: 📤 上传 .alf 文件
        uses: actions/upload-artifact@v4
        with:
          name: unity-alf
          path: ./*.alf
          retention-days: 7
